/**
 * قاموس نصوص واجهة قضية «آخر رحلة» (ar/en) — مستقل تماماً عن قاموس i18n
 * العام، لأن هذي النصوص خاصة بمسار هذي القضية فقط.
 */
import type { Lang } from "@/i18n";

export const lastTripStrings = {
  ar: {
    backToCases: "رجوع للقضايا",
    fileCode: "ملف {{code}} · سري",
    lobbyEyebrow: "غرفة اللاعبين",
    lobbyDefaultTitle: "آخر رحلة",
    inOtherRoom: "أنت حالياً داخل غرفة قضية ثانية. اخرج منها أول عشان تفتح غرفة «آخر رحلة».",
    leaveCurrentRoom: "اخرج من الغرفة الحالية",
    backToMyRoom: "رجوع لغرفتي الحالية",
    roomCode: "رمز الغرفة",
    copyCode: "نسخ الرمز",
    shareCode: "عطِ ربعك هالرمز عشان يدخلون نفس الغرفة. بعدها المضيف يبدأ القضية.",
    startCase: "ابدأ القضية",
    waitForHost: "انتظر المضيف يبدأ القضية",
    investigatorsInRoom: "المحققون بالغرفة",
    host: "المضيف",
    openNewRoom: "افتح غرفة جديدة",
    joinWithCode: "انضم برمز",
    playSolo: "العب بدون غرفة (فردي)",
    newRoomTitle: "غرفة جديدة",
    joinRoomTitle: "دخول غرفة",
    createRoomCta: "افتح غرفة آخر رحلة",
    joinRoomCta: "انضم لغرفة",
    close: "إغلاق",
    yourName: "اسمك بالتحقيق",
    namePlaceholder: "مثال: أبو خالد",
    roomCodeLabel: "رمز الغرفة (6 أرقام)",
    nameTooShort: "اكتب اسم من حرفين على الأقل",
    codeMustBe6: "رمز الغرفة لازم يكون 6 أرقام",
    couldNotJoin: "ما قدرنا ندخلك الغرفة",
    loadingDots: "لحظة...",
    createRoomSubmit: "أنشئ الغرفة",
    joinRoomSubmit: "دخول",

    skipWaiting: "تخطَّ الانتظار",
    skipIntro: "تخطي المقدمة",
    startInvestigation: "ابدأ التحقيق",

    sceneEyebrow: "معاينة الموقع",
    sceneTitle: "مسرح الجريمة — {{title}}",
    sceneDesc:
      "محطة طريق على الخط السريع بعد منتصف الليل. تحرّك بالضغط على الأبواب والأشياء داخل الصورة نفسها. دوّر بعينك — الأدلة مخفية داخل المشاهد نفسها.",
    yourRole: "دورك: {{role}}",
    evidenceCount: "الأدلة {{found}}/{{total}}",
    accusation: "الاتهام",
    characters: "الشخصيات",
    caseStore: "متجر القضايا",
    nothingHere: "ماكو شي مهم هنا",
    sceneAlt: "مشهد داخل محطة الطريق",
    moveHint: "التحرك داخل المحطة",
    inspectHint: "فحص تفصيلة داخل المحطة",
    goBack: "رجوع",
    newEvidence: "دليل جديد",
    detailedAnalysis: "الفحص التفصيلي",
    runAnalysis: "فحص تفصيلي (قدرة دورك)",
    addedToNotebook: "انضاف الدليل لدفتر القضية ويشوفه كل الفريق.",
    backToScene: "رجوع للمشهد",
    moveTip: "تحرّك بالضغط على الأشياء والأبواب نفسها داخل الصورة.",
    abdullahFileEyebrow: "ملف التحقيق — عبدالله",
    abdullahFileTitle: "بيانات جهاز عبدالله",
    checkCallLog: "فحص سجل المكالمات",
    callLogNote: "المكالمة طويلة… بس فيها انقطاع قصير ما له تفسير حتى الآن.",
    callLog1: "01:12 — مكالمة صادرة (٢٦ دقيقة) — تبدأ بشكل طبيعي",
    callLog2: "01:31 — انقطاع قصير (٤ دقائق) — بدون سبب مسجّل",
    callLog3: "01:35 — رجوع نفس المكالمة (١٢ دقيقة)",
    callLog4: "01:47 — نهاية المكالمة",

    suspectFilesEyebrow: "ملفات الشخصيات",
    suspectsTitle: "الشخصيات — {{title}}",
    suspectsDesc: "ملف الضحية وخمس ملفات للموجودين بالمحطة تلك الليلة. كل ملف فيه اللي معلن بس — الباقي يطلع بالاستجواب.",
    suspectTotal: "المشتبه فيهم {{n}}",
    interrogationsCount: "الاستجوابات {{count}}/{{total}}",
    crimeScene: "مسرح الجريمة",
    victim: "الضحية",
    yearsOld: "{{n}} سنة",
    notInterrogatable: "غير قابل للاستجواب",
    whereWere: "وين كان: {{where}}",
    interrogate: "استجواب {{name}}",
    interrogateDone: "خلص استجواب {{name}}",
    photoOf: "صورة {{name}}",

    interrogationRoom: "غرفة الاستجواب",
    timeRemainingAria: "الوقت المتبقي لاستجواب هذا المشتبه فيه",
    finishInterrogation: "أنهِ الاستجواب",
    startWithQuestion: "ابدأ بسؤال. اسأله بلهجتك عادي: «وين كنت وقتها؟»، «شنو كنت تسوي؟»",
    watchOnly: "المحقق هو اللي يسأل — أنت تشوف السؤال والرد ومؤشر التوتر لحظة بلحظة.",
    investigator: "المحقق",
    thinking: "…{{name}} يفكر",
    contradictionFlag: "في شي بكلامه ما يركب مع الدليل",
    pendingConfront: "مواجهة مرفقة مع سؤالك الجاي.",
    interrogationExpired: "خلص وقت استجواب {{name}} — ما تقدر ترسل أسئلة جديدة له.",
    questionPlaceholder: "اكتب سؤالك…",
    questionPlaceholderExpired: "انتهى وقت هذا المشتبه فيه",
    send: "إرسال",
    interrogateDeniedPrefix: "إرسال الأسئلة من اختصاص المحقق — ",
    confrontWithEvidence: "مواجهة بدليل",
    noEvidenceYet: "ما عندك أدلة مكتشفة بعد. روح مسرح الجريمة أول.",
    whatDoYouSay: "شنو تقول عن {{title}}؟",
    confrontDone: "تمت المواجهة",
    confrontWithWitness: "مواجهة بأقوال شاهد",
    noWitnessClaims: "ما فيه أقوال شهود تخص {{name}}.",
    whatsYourReply: "{{text}} شنو ردك؟",
    contradictionsBoard: "التناقضات وربط الأقوال",
    noContradictionsYet: "ما انرصد أي تناقض حتى الآن — تابع الاستجواب.",
    suspectsListEyebrow: "المشتبه فيهم",
    noSuspectAtId: "ما فيه مشتبه فيه بهذا المعرّف.",
    backToSuspects: "رجوع للشخصيات",
    noDetective: "ما فيه محقق بالفريق",
    noDetectiveDesc:
      "الاستجواب يحتاج لاعب بدور «المحقق». رجّعوا لصفحة الشخصيات وتأكدوا إن كل اللاعبين داخلين وأخذوا أدوارهم، وبعدها ارجعوا للاستجواب.",
    repeatedConfront: "هذي المواجهة صارت قبل — ما تنفع تتكرر.",

    finalStage: "المرحلة الأخيرة",
    accusationTitle: "الاختيار النهائي — {{title}}",
    accusationDescLocked: "لازم تخلصون استجواب كل الشخصيات قبل الاتهام.",
    accusationDescResult: "تم تسجيل اتهام الفريق — النتيجة تحت.",
    accusationDescReady: "خلصتوا استجواب كل الشخصيات. اختاروا منو تتهمونه.",
    accusationLocked: "الاتهام مقفل — باقي {{n}} استجواب.",
    accusationReasonsEyebrow: "أسباب الاتهام (اختياري)",
    accusationReasonsDesc: "اختاروا الأدلة اللي بنيتوا عليها الاتهام.",
    youPicked: "اخترتوا: {{name}}",
    pickSuspect: "اختاروا متهم من فوق.",
    confirmAccusation: "تأكيد الاتهام",
    recording: "جاري التسجيل…",
    accusationRoomError: "الاتهام النهائي يحتاج غرفة قضية «آخر رحلة» — افتح غرفة أو ادخل برمز.",
    accusationJudgeError: "ما قدرنا نسجّل الاتهام — تأكد إنك داخل غرفة القضية وجرب مرة ثانية.",
    correctAccusation: "اتهام صحيح",
    wrongAccusation: "الاتهام غير صحيح",
    correctAccusationDesc:
      "وصلتوا للقاتل: {{name}}. ربطتوا الأدلة مع التناقضات بكلامه، والخط الزمني اللي حاول يركبه ما ثبت أمام اللي اكتشفتوه.",
    wrongAccusationDesc:
      "{{name}} مب القاتل. الأدلة والتناقضات تشير لشخص ثاني — راجعوا كلام الشهود والخط الزمني وأعيدوا الاتهام، أو شوفوا النهاية.",
    attemptsCount: "عدد محاولات الاتهام: {{n}}",
    revealSolution: "كشف الحل",
    retryAccusation: "إعادة الاتهام",
    watchEnding: "مشاهدة النهاية",

    endingLockCheckingRoom: "جاري التحقق من الغرفة…",
    endingLocked: "النهاية مقفلة",
    endingLockedDesc: "شاشة النهاية تفتح لفريق الغرفة بعد ما يخلصون الاتهام النهائي.",
    casesLink: "القضايا",
    endingEyebrow: "نهاية القضية — {{title}}",
    culpritLabel: "القاتل: {{name}}",
    fullSolution: "الحل الكامل",
    caseEnded: "انتهت القضية.",
    beatsProgress: "{{shown}} من {{total}}",
    continue_: "كمّل",

    roleGateEyebrow: "دورك في القضية",
    specialAbility: "قدرتك الخاصة",
    deviceOnlyRole: "هذا الدور خاص بجهازك — ما أحد بالفريق يشوفه",
    understoodContinue: "فهمت دوري — متابعة",
    noRoleYetTitle: "ما وصلك دور بعد",
    noRoleYetDesc:
      "توزيع الأدوار ما اكتمل، أو الأدوار الستة كلها محجوزة. ارجع لصفحة القضية وتأكد من عدد اللاعبين، وبعدها جرب مرة ثانية.",
    waitingRoom: "غرفة الانتظار",
    assigningRoles: "جاري توزيع الأدوار…",
  },
  en: {
    backToCases: "Back to cases",
    fileCode: "File {{code}} · Confidential",
    lobbyEyebrow: "Player Lobby",
    lobbyDefaultTitle: "The Last Trip",
    inOtherRoom: "You're currently in another case's room. Leave it first to open a «The Last Trip» room.",
    leaveCurrentRoom: "Leave current room",
    backToMyRoom: "Back to my current room",
    roomCode: "Room Code",
    copyCode: "Copy code",
    shareCode: "Give your friends this code so they join the same room. Then the host starts the case.",
    startCase: "Start the case",
    waitForHost: "Waiting for the host to start the case",
    investigatorsInRoom: "Investigators in the room",
    host: "Host",
    openNewRoom: "Open a new room",
    joinWithCode: "Join with a code",
    playSolo: "Play without a room (solo)",
    newRoomTitle: "New Room",
    joinRoomTitle: "Join Room",
    createRoomCta: "Open a Last Trip room",
    joinRoomCta: "Join a room",
    close: "Close",
    yourName: "Your name for the investigation",
    namePlaceholder: "e.g. Abu Khalid",
    roomCodeLabel: "Room code (6 digits)",
    nameTooShort: "Enter a name with at least 2 characters",
    codeMustBe6: "The room code must be 6 digits",
    couldNotJoin: "We couldn't get you into the room",
    loadingDots: "One sec...",
    createRoomSubmit: "Create room",
    joinRoomSubmit: "Join",

    skipWaiting: "Skip wait",
    skipIntro: "Skip intro",
    startInvestigation: "Start the investigation",

    sceneEyebrow: "Location Survey",
    sceneTitle: "Crime Scene — {{title}}",
    sceneDesc:
      "A highway rest stop after midnight. Move around by clicking doors and objects right inside the image. Look closely — the evidence is hidden within the scenes themselves.",
    yourRole: "Your role: {{role}}",
    evidenceCount: "Evidence {{found}}/{{total}}",
    accusation: "Accusation",
    characters: "Characters",
    caseStore: "Case Store",
    nothingHere: "Nothing important here",
    sceneAlt: "A scene inside the highway rest stop",
    moveHint: "Move around the station",
    inspectHint: "Inspect a detail inside the station",
    goBack: "Back",
    newEvidence: "New Evidence",
    detailedAnalysis: "Detailed Analysis",
    runAnalysis: "Run detailed analysis (your role's ability)",
    addedToNotebook: "The evidence was added to the case notebook and the whole team can see it.",
    backToScene: "Back to the scene",
    moveTip: "Move around by clicking the objects and doors right inside the image.",
    abdullahFileEyebrow: "Investigation File — Abdullah",
    abdullahFileTitle: "Abdullah's phone data",
    checkCallLog: "Check the call log",
    callLogNote: "The call is long… but has a short gap in it with no explanation so far.",
    callLog1: "01:12 — Outgoing call (26 min) — starts normally",
    callLog2: "01:31 — Short gap (4 min) — no recorded reason",
    callLog3: "01:35 — Same call resumes (12 min)",
    callLog4: "01:47 — Call ends",

    suspectFilesEyebrow: "Character Files",
    suspectsTitle: "Characters — {{title}}",
    suspectsDesc: "The victim's file and five files for those present at the station that night. Each file has only what's public — the rest comes out during questioning.",
    suspectTotal: "Suspects {{n}}",
    interrogationsCount: "Interrogations {{count}}/{{total}}",
    crimeScene: "Crime Scene",
    victim: "Victim",
    yearsOld: "{{n}} years old",
    notInterrogatable: "Cannot be interrogated",
    whereWere: "Where they were: {{where}}",
    interrogate: "Interrogate {{name}}",
    interrogateDone: "Finished interrogating {{name}}",
    photoOf: "Photo of {{name}}",

    interrogationRoom: "Interrogation Room",
    timeRemainingAria: "Time remaining to interrogate this suspect",
    finishInterrogation: "Finish interrogation",
    startWithQuestion: "Start with a question. Ask naturally: \"Where were you at the time?\", \"What were you doing?\"",
    watchOnly: "Only the detective asks questions — you watch the question, reply, and stress meter live.",
    investigator: "Detective",
    thinking: "…{{name}} is thinking",
    contradictionFlag: "Something in this doesn't line up with the evidence",
    pendingConfront: "A confrontation is attached to your next question.",
    interrogationExpired: "{{name}}'s interrogation time is up — you can't send new questions to them.",
    questionPlaceholder: "Type your question…",
    questionPlaceholderExpired: "This suspect's time is up",
    send: "Send",
    interrogateDeniedPrefix: "Sending questions is the detective's job — ",
    confrontWithEvidence: "Confront with evidence",
    noEvidenceYet: "You don't have any discovered evidence yet. Go to the crime scene first.",
    whatDoYouSay: "What do you say about {{title}}?",
    confrontDone: "Confronted",
    confrontWithWitness: "Confront with witness statement",
    noWitnessClaims: "There are no witness statements about {{name}}.",
    whatsYourReply: "{{text}} What's your reply?",
    contradictionsBoard: "Contradictions & Statement Links",
    noContradictionsYet: "No contradictions found yet — keep questioning.",
    suspectsListEyebrow: "Suspects",
    noSuspectAtId: "No suspect exists with this ID.",
    backToSuspects: "Back to characters",
    noDetective: "No detective on the team",
    noDetectiveDesc:
      "Interrogation needs a player with the «Detective» role. Go back to the characters page and make sure all players have joined and taken their roles, then come back to the interrogation.",
    repeatedConfront: "This confrontation already happened — it can't be repeated.",

    finalStage: "Final Stage",
    accusationTitle: "Final Choice — {{title}}",
    accusationDescLocked: "You must finish interrogating everyone before you can accuse.",
    accusationDescResult: "Your team's accusation has been recorded — the result is below.",
    accusationDescReady: "You've finished interrogating everyone. Choose who to accuse.",
    accusationLocked: "Accusation locked — {{n}} interrogation(s) left.",
    accusationReasonsEyebrow: "Reasons for the accusation (optional)",
    accusationReasonsDesc: "Choose the evidence you're basing the accusation on.",
    youPicked: "You chose: {{name}}",
    pickSuspect: "Choose a suspect above.",
    confirmAccusation: "Confirm accusation",
    recording: "Recording…",
    accusationRoomError: "The final accusation needs a «The Last Trip» case room — open a room or join with a code.",
    accusationJudgeError: "We couldn't record the accusation — make sure you're in the case room and try again.",
    correctAccusation: "Correct accusation",
    wrongAccusation: "Wrong accusation",
    correctAccusationDesc:
      "You found the killer: {{name}}. You connected the evidence with the contradictions in their story, and the timeline they tried to build didn't hold up against what you uncovered.",
    wrongAccusationDesc:
      "{{name}} isn't the killer. The evidence and contradictions point to someone else — review the witness statements and timeline and accuse again, or watch the ending.",
    attemptsCount: "Number of accusation attempts: {{n}}",
    revealSolution: "Reveal the solution",
    retryAccusation: "Accuse again",
    watchEnding: "Watch the ending",

    endingLockCheckingRoom: "Checking the room…",
    endingLocked: "Ending locked",
    endingLockedDesc: "The ending screen opens for the room's team after they finish the final accusation.",
    casesLink: "Cases",
    endingEyebrow: "Case Ending — {{title}}",
    culpritLabel: "The killer: {{name}}",
    fullSolution: "Full solution",
    caseEnded: "The case has ended.",
    beatsProgress: "{{shown}} of {{total}}",
    continue_: "Continue",

    roleGateEyebrow: "Your Role in the Case",
    specialAbility: "Your special ability",
    deviceOnlyRole: "This role is specific to your device — no one else on the team can see it",
    understoodContinue: "Got my role — continue",
    noRoleYetTitle: "No role assigned yet",
    noRoleYetDesc:
      "Role assignment isn't finished, or all six roles are taken. Go back to the case page and check the player count, then try again.",
    waitingRoom: "Waiting room",
    assigningRoles: "Assigning roles…",
  },
} as const;

type LastTripDict = typeof lastTripStrings.ar;
export type LastTripStringKey = keyof LastTripDict;

function fill(text: string, vars?: Record<string, string | number>): string {
  if (!vars) return text;
  return text.replace(/\{\{(\w+)\}\}/g, (_, k: string) =>
    vars[k] === undefined ? `{{${k}}}` : String(vars[k]),
  );
}

/** ترجمة نصوص واجهة قضية «آخر رحلة» فقط، مع دعم استبدال {{var}}. */
export function lastTripT(
  lang: Lang,
  key: LastTripStringKey,
  vars?: Record<string, string | number>,
): string {
  const dict = lastTripStrings[lang] ?? lastTripStrings.ar;
  const text = (dict as Record<string, string>)[key] ?? (lastTripStrings.ar as Record<string, string>)[key] ?? key;
  return fill(text, vars);
}
