/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccusationRouteImport } from './routes/accusation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaseRouteImport } from './routes/case'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPaddleEventsRouteImport } from './routes/admin.paddle-events'
import { Route as DevFloor13RouteImport } from './routes/dev.floor13'
import { Route as InterrogationSuspectIdRouteImport } from './routes/interrogation.$suspectId'
import { Route as LastTripAccusationRouteImport } from './routes/last-trip.accusation'
import { Route as LastTripEndingRouteImport } from './routes/last-trip.ending'
import { Route as LastTripIntroRouteImport } from './routes/last-trip.intro'
import { Route as LastTripLobbyRouteImport } from './routes/last-trip.lobby'
import { Route as LastTripSceneRouteImport } from './routes/last-trip.scene'
import { Route as LastTripSuspectsRouteImport } from './routes/last-trip.suspects'
import { Route as PurchaseCaseIdRouteImport } from './routes/purchase.$caseId'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle-webhook'
import { Route as LastTripInterrogationSuspectIdRouteImport } from './routes/last-trip.interrogation.$suspectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccusationRoute = AccusationRouteImport.update({
  id: '/accusation',
  path: '/accusation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaddleEventsRoute = AdminPaddleEventsRouteImport.update({
  id: '/admin/paddle-events',
  path: '/admin/paddle-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFloor13Route = DevFloor13RouteImport.update({
  id: '/dev/floor13',
  path: '/dev/floor13',
  getParentRoute: () => rootRouteImport,
} as any)
const InterrogationSuspectIdRoute = InterrogationSuspectIdRouteImport.update({
  id: '/interrogation/$suspectId',
  path: '/interrogation/$suspectId',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripAccusationRoute = LastTripAccusationRouteImport.update({
  id: '/last-trip/accusation',
  path: '/last-trip/accusation',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripEndingRoute = LastTripEndingRouteImport.update({
  id: '/last-trip/ending',
  path: '/last-trip/ending',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripIntroRoute = LastTripIntroRouteImport.update({
  id: '/last-trip/intro',
  path: '/last-trip/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripLobbyRoute = LastTripLobbyRouteImport.update({
  id: '/last-trip/lobby',
  path: '/last-trip/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripSceneRoute = LastTripSceneRouteImport.update({
  id: '/last-trip/scene',
  path: '/last-trip/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripSuspectsRoute = LastTripSuspectsRouteImport.update({
  id: '/last-trip/suspects',
  path: '/last-trip/suspects',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseCaseIdRoute = PurchaseCaseIdRouteImport.update({
  id: '/purchase/$caseId',
  path: '/purchase/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LastTripInterrogationSuspectIdRoute =
  LastTripInterrogationSuspectIdRouteImport.update({
    id: '/last-trip/interrogation/$suspectId',
    path: '/last-trip/interrogation/$suspectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accusation': typeof AccusationRoute
  '/auth': typeof AuthRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/lobby': typeof LobbyRoute
  '/notebook': typeof NotebookRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/purchases': typeof PurchasesRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reveal': typeof RevealRoute
  '/roles': typeof RolesRoute
  '/scene': typeof SceneRoute
  '/terms': typeof TermsRoute
  '/admin/paddle-events': typeof AdminPaddleEventsRoute
  '/dev/floor13': typeof DevFloor13Route
  '/interrogation/$suspectId': typeof InterrogationSuspectIdRoute
  '/last-trip/accusation': typeof LastTripAccusationRoute
  '/last-trip/ending': typeof LastTripEndingRoute
  '/last-trip/intro': typeof LastTripIntroRoute
  '/last-trip/lobby': typeof LastTripLobbyRoute
  '/last-trip/scene': typeof LastTripSceneRoute
  '/last-trip/suspects': typeof LastTripSuspectsRoute
  '/purchase/$caseId': typeof PurchaseCaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/last-trip/interrogation/$suspectId': typeof LastTripInterrogationSuspectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accusation': typeof AccusationRoute
  '/auth': typeof AuthRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/lobby': typeof LobbyRoute
  '/notebook': typeof NotebookRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/purchases': typeof PurchasesRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reveal': typeof RevealRoute
  '/roles': typeof RolesRoute
  '/scene': typeof SceneRoute
  '/terms': typeof TermsRoute
  '/admin/paddle-events': typeof AdminPaddleEventsRoute
  '/dev/floor13': typeof DevFloor13Route
  '/interrogation/$suspectId': typeof InterrogationSuspectIdRoute
  '/last-trip/accusation': typeof LastTripAccusationRoute
  '/last-trip/ending': typeof LastTripEndingRoute
  '/last-trip/intro': typeof LastTripIntroRoute
  '/last-trip/lobby': typeof LastTripLobbyRoute
  '/last-trip/scene': typeof LastTripSceneRoute
  '/last-trip/suspects': typeof LastTripSuspectsRoute
  '/purchase/$caseId': typeof PurchaseCaseIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/last-trip/interrogation/$suspectId': typeof LastTripInterrogationSuspectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accusation': typeof AccusationRoute
  '/auth': typeof AuthRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/lobby': typeof LobbyRoute
  '/notebook': typeof NotebookRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/purchases': typeof PurchasesRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reveal': typeof RevealRoute
  '/roles': typeof RolesRoute
  '/scene': typeof SceneRoute
  '/terms': typeof TermsRoute
  '/admin/paddle-events': typeof AdminPaddleEventsRoute
  '/dev/floor13': typeof DevFloor13Route
  '/interrogation/$suspectId': typeof InterrogationSuspectIdRoute
  '/last-trip/accusation': typeof LastTripAccusationRoute
  '/last-trip/ending': typeof LastTripEndingRoute
  '/last-trip/intro': typeof LastTripIntroRoute
  '/last-trip/lobby': typeof LastTripLobbyRoute
  '/last-trip/scene': typeof LastTripSceneRoute
  '/last-trip/suspects': typeof LastTripSuspectsRoute
  '/purchase/$caseId': typeof PurchaseCaseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/last-trip/interrogation/$suspectId': typeof LastTripInterrogationSuspectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accusation'
    | '/auth'
    | '/case'
    | '/cases'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/intro'
    | '/lobby'
    | '/notebook'
    | '/play'
    | '/privacy'
    | '/purchases'
    | '/refund'
    | '/reset-password'
    | '/reveal'
    | '/roles'
    | '/scene'
    | '/terms'
    | '/admin/paddle-events'
    | '/dev/floor13'
    | '/interrogation/$suspectId'
    | '/last-trip/accusation'
    | '/last-trip/ending'
    | '/last-trip/intro'
    | '/last-trip/lobby'
    | '/last-trip/scene'
    | '/last-trip/suspects'
    | '/purchase/$caseId'
    | '/admin/'
    | '/api/public/paddle-webhook'
    | '/last-trip/interrogation/$suspectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accusation'
    | '/auth'
    | '/case'
    | '/cases'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/intro'
    | '/lobby'
    | '/notebook'
    | '/play'
    | '/privacy'
    | '/purchases'
    | '/refund'
    | '/reset-password'
    | '/reveal'
    | '/roles'
    | '/scene'
    | '/terms'
    | '/admin/paddle-events'
    | '/dev/floor13'
    | '/interrogation/$suspectId'
    | '/last-trip/accusation'
    | '/last-trip/ending'
    | '/last-trip/intro'
    | '/last-trip/lobby'
    | '/last-trip/scene'
    | '/last-trip/suspects'
    | '/purchase/$caseId'
    | '/admin'
    | '/api/public/paddle-webhook'
    | '/last-trip/interrogation/$suspectId'
  id:
    | '__root__'
    | '/'
    | '/accusation'
    | '/auth'
    | '/case'
    | '/cases'
    | '/checkout'
    | '/contact'
    | '/dashboard'
    | '/intro'
    | '/lobby'
    | '/notebook'
    | '/play'
    | '/privacy'
    | '/purchases'
    | '/refund'
    | '/reset-password'
    | '/reveal'
    | '/roles'
    | '/scene'
    | '/terms'
    | '/admin/paddle-events'
    | '/dev/floor13'
    | '/interrogation/$suspectId'
    | '/last-trip/accusation'
    | '/last-trip/ending'
    | '/last-trip/intro'
    | '/last-trip/lobby'
    | '/last-trip/scene'
    | '/last-trip/suspects'
    | '/purchase/$caseId'
    | '/admin/'
    | '/api/public/paddle-webhook'
    | '/last-trip/interrogation/$suspectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccusationRoute: typeof AccusationRoute
  AuthRoute: typeof AuthRoute
  CaseRoute: typeof CaseRoute
  CasesRoute: typeof CasesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  IntroRoute: typeof IntroRoute
  LobbyRoute: typeof LobbyRoute
  NotebookRoute: typeof NotebookRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  PurchasesRoute: typeof PurchasesRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevealRoute: typeof RevealRoute
  RolesRoute: typeof RolesRoute
  SceneRoute: typeof SceneRoute
  TermsRoute: typeof TermsRoute
  AdminPaddleEventsRoute: typeof AdminPaddleEventsRoute
  DevFloor13Route: typeof DevFloor13Route
  InterrogationSuspectIdRoute: typeof InterrogationSuspectIdRoute
  LastTripAccusationRoute: typeof LastTripAccusationRoute
  LastTripEndingRoute: typeof LastTripEndingRoute
  LastTripIntroRoute: typeof LastTripIntroRoute
  LastTripLobbyRoute: typeof LastTripLobbyRoute
  LastTripSceneRoute: typeof LastTripSceneRoute
  LastTripSuspectsRoute: typeof LastTripSuspectsRoute
  PurchaseCaseIdRoute: typeof PurchaseCaseIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
  LastTripInterrogationSuspectIdRoute: typeof LastTripInterrogationSuspectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accusation': {
      id: '/accusation'
      path: '/accusation'
      fullPath: '/accusation'
      preLoaderRoute: typeof AccusationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/paddle-events': {
      id: '/admin/paddle-events'
      path: '/admin/paddle-events'
      fullPath: '/admin/paddle-events'
      preLoaderRoute: typeof AdminPaddleEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/floor13': {
      id: '/dev/floor13'
      path: '/dev/floor13'
      fullPath: '/dev/floor13'
      preLoaderRoute: typeof DevFloor13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrogation/$suspectId': {
      id: '/interrogation/$suspectId'
      path: '/interrogation/$suspectId'
      fullPath: '/interrogation/$suspectId'
      preLoaderRoute: typeof InterrogationSuspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/accusation': {
      id: '/last-trip/accusation'
      path: '/last-trip/accusation'
      fullPath: '/last-trip/accusation'
      preLoaderRoute: typeof LastTripAccusationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/ending': {
      id: '/last-trip/ending'
      path: '/last-trip/ending'
      fullPath: '/last-trip/ending'
      preLoaderRoute: typeof LastTripEndingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/intro': {
      id: '/last-trip/intro'
      path: '/last-trip/intro'
      fullPath: '/last-trip/intro'
      preLoaderRoute: typeof LastTripIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/lobby': {
      id: '/last-trip/lobby'
      path: '/last-trip/lobby'
      fullPath: '/last-trip/lobby'
      preLoaderRoute: typeof LastTripLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/scene': {
      id: '/last-trip/scene'
      path: '/last-trip/scene'
      fullPath: '/last-trip/scene'
      preLoaderRoute: typeof LastTripSceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/suspects': {
      id: '/last-trip/suspects'
      path: '/last-trip/suspects'
      fullPath: '/last-trip/suspects'
      preLoaderRoute: typeof LastTripSuspectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$caseId': {
      id: '/purchase/$caseId'
      path: '/purchase/$caseId'
      fullPath: '/purchase/$caseId'
      preLoaderRoute: typeof PurchaseCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/last-trip/interrogation/$suspectId': {
      id: '/last-trip/interrogation/$suspectId'
      path: '/last-trip/interrogation/$suspectId'
      fullPath: '/last-trip/interrogation/$suspectId'
      preLoaderRoute: typeof LastTripInterrogationSuspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccusationRoute: AccusationRoute,
  AuthRoute: AuthRoute,
  CaseRoute: CaseRoute,
  CasesRoute: CasesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  IntroRoute: IntroRoute,
  LobbyRoute: LobbyRoute,
  NotebookRoute: NotebookRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  PurchasesRoute: PurchasesRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevealRoute: RevealRoute,
  RolesRoute: RolesRoute,
  SceneRoute: SceneRoute,
  TermsRoute: TermsRoute,
  AdminPaddleEventsRoute: AdminPaddleEventsRoute,
  DevFloor13Route: DevFloor13Route,
  InterrogationSuspectIdRoute: InterrogationSuspectIdRoute,
  LastTripAccusationRoute: LastTripAccusationRoute,
  LastTripEndingRoute: LastTripEndingRoute,
  LastTripIntroRoute: LastTripIntroRoute,
  LastTripLobbyRoute: LastTripLobbyRoute,
  LastTripSceneRoute: LastTripSceneRoute,
  LastTripSuspectsRoute: LastTripSuspectsRoute,
  PurchaseCaseIdRoute: PurchaseCaseIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
  LastTripInterrogationSuspectIdRoute: LastTripInterrogationSuspectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
