/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccusationRouteImport } from './routes/accusation'
import { Route as CaseRouteImport } from './routes/case'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SceneRouteImport } from './routes/scene'
import { Route as InterrogationSuspectIdRouteImport } from './routes/interrogation.$suspectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccusationRoute = AccusationRouteImport.update({
  id: '/accusation',
  path: '/accusation',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneRoute = SceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => rootRouteImport,
} as any)
const InterrogationSuspectIdRoute = InterrogationSuspectIdRouteImport.update({
  id: '/interrogation/$suspectId',
  path: '/interrogation/$suspectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accusation': typeof AccusationRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/lobby': typeof LobbyRoute
  '/notebook': typeof NotebookRoute
  '/play': typeof PlayRoute
  '/reveal': typeof RevealRoute
  '/roles': typeof RolesRoute
  '/scene': typeof SceneRoute
  '/interrogation/$suspectId': typeof InterrogationSuspectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accusation': typeof AccusationRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/lobby': typeof LobbyRoute
  '/notebook': typeof NotebookRoute
  '/play': typeof PlayRoute
  '/reveal': typeof RevealRoute
  '/roles': typeof RolesRoute
  '/scene': typeof SceneRoute
  '/interrogation/$suspectId': typeof InterrogationSuspectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accusation': typeof AccusationRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/intro': typeof IntroRoute
  '/lobby': typeof LobbyRoute
  '/notebook': typeof NotebookRoute
  '/play': typeof PlayRoute
  '/reveal': typeof RevealRoute
  '/roles': typeof RolesRoute
  '/scene': typeof SceneRoute
  '/interrogation/$suspectId': typeof InterrogationSuspectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accusation'
    | '/case'
    | '/cases'
    | '/dashboard'
    | '/intro'
    | '/lobby'
    | '/notebook'
    | '/play'
    | '/reveal'
    | '/roles'
    | '/scene'
    | '/interrogation/$suspectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accusation'
    | '/case'
    | '/cases'
    | '/dashboard'
    | '/intro'
    | '/lobby'
    | '/notebook'
    | '/play'
    | '/reveal'
    | '/roles'
    | '/scene'
    | '/interrogation/$suspectId'
  id:
    | '__root__'
    | '/'
    | '/accusation'
    | '/case'
    | '/cases'
    | '/dashboard'
    | '/intro'
    | '/lobby'
    | '/notebook'
    | '/play'
    | '/reveal'
    | '/roles'
    | '/scene'
    | '/interrogation/$suspectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccusationRoute: typeof AccusationRoute
  CaseRoute: typeof CaseRoute
  CasesRoute: typeof CasesRoute
  DashboardRoute: typeof DashboardRoute
  IntroRoute: typeof IntroRoute
  LobbyRoute: typeof LobbyRoute
  NotebookRoute: typeof NotebookRoute
  PlayRoute: typeof PlayRoute
  RevealRoute: typeof RevealRoute
  RolesRoute: typeof RolesRoute
  SceneRoute: typeof SceneRoute
  InterrogationSuspectIdRoute: typeof InterrogationSuspectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accusation': {
      id: '/accusation'
      path: '/accusation'
      fullPath: '/accusation'
      preLoaderRoute: typeof AccusationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene': {
      id: '/scene'
      path: '/scene'
      fullPath: '/scene'
      preLoaderRoute: typeof SceneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrogation/$suspectId': {
      id: '/interrogation/$suspectId'
      path: '/interrogation/$suspectId'
      fullPath: '/interrogation/$suspectId'
      preLoaderRoute: typeof InterrogationSuspectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccusationRoute: AccusationRoute,
  CaseRoute: CaseRoute,
  CasesRoute: CasesRoute,
  DashboardRoute: DashboardRoute,
  IntroRoute: IntroRoute,
  LobbyRoute: LobbyRoute,
  NotebookRoute: NotebookRoute,
  PlayRoute: PlayRoute,
  RevealRoute: RevealRoute,
  RolesRoute: RolesRoute,
  SceneRoute: SceneRoute,
  InterrogationSuspectIdRoute: InterrogationSuspectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
